[build]
  # The base directory cannot be the project root since if it is, Netlify will pick the `runtime.txt` file which is not
  # in Netlify's format. It is instead in Heroku's format.
  base = "frontend/"
  publish = "dist/"
  command = "make -C .. netlify"
  environment = { NODE_VERSION = "12", PRESTIGE_BACKEND = "/api/", PYTHON_VERSION = "3.7" }

[[redirects]]
  from = "/api/*"
  to = "http://api.prestigemad.com/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }
  # TODO: Add a secret to use signed proxy. See <https://docs.netlify.com/routing/redirects/rewrites-proxies/#signed-proxy-redirects>

[[redirects]]
  from = "/a/*"
  to = "http://api.prestigemad.com/a/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }
  # TODO: Add a secret to use signed proxy. See <https://docs.netlify.com/routing/redirects/rewrites-proxies/#signed-proxy-redirects>

# Following is required for SPAs that handle routing client-side.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
