# Generated by Django 3.2.5 on 2021-09-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_githubidentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubidentity',
            options={'verbose_name': 'GitHub Identity', 'verbose_name_plural': 'GitHub Identities'},
        ),
        migrations.AddField(
            model_name='githubidentity',
            name='avatar_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='githubidentity',
            name='db_id',
            field=models.IntegerField(default=-1, help_text='The numeric database ID of the user on GitHub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubidentity',
            name='user_handle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubidentity',
            name='uid',
            field=models.CharField(help_text='The newer string ID of the user on GitHub', max_length=100),
        ),
        migrations.AlterField(
            model_name='githubidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_ids', to=settings.AUTH_USER_MODEL),
        ),
    ]
