# Generated by Django 3.2.5 on 2021-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_auto_20210918_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubidentity',
            name='uid',
            field=models.CharField(help_text='The newer string ID of the user on GitHub', max_length=300),
        ),
        migrations.AlterField(
            model_name='githubidentity',
            name='user_handle',
            field=models.CharField(max_length=400),
        ),
    ]
