# Generated by Django 3.1.4 on 2021-01-01 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0003_add_slug_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('user', 'name'), ('user', 'slug')},
        ),
    ]
