# Generated by Django 3.1.4 on 2021-01-02 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_add_unique_user_name_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Name has to be a valid identifier and so can only contain alphanumerics, hyphen and underscore characters.', regex='^[-_a-zA-Z0-9]+$')]),
        ),
    ]
