"""
Django settings for prestige project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

UNIVERSE = os.environ.get("PRESTIGE_UNIVERSE", "").lower()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

if UNIVERSE != "test":
	_missing_env_vars = {
		"PRESTIGE_DATABASE_URL",
		"PRESTIGE_SECRET_KEY",
		"PRESTIGE_CORS_ORIGINS",
	} - os.environ.keys()

	if _missing_env_vars:
		raise ValueError("Missing required env vars: %r" % _missing_env_vars)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "test-key" if UNIVERSE == "test" else os.getenv("PRESTIGE_SECRET_KEY")
if not SECRET_KEY:
	raise ValueError("Missing secret key. Please set the env variable PRESTIGE_SECRET_KEY.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("PRESTIGE_ENV", "production") != "production"

ALLOWED_HOSTS = [
	"localhost",
	"127.0.0.1",
] if DEBUG else [s.strip() for s in os.getenv("PRESTIGE_ALLOWED_HOSTS", "").split(",") if s and not s.isspace()]

# Application definition

INSTALLED_APPS = [
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"django.contrib.sites",
	"corsheaders",
	"proxy",
	"auth_api",
	"storage",
	"allauth",
	"allauth.account",
	"allauth.socialaccount",
	"allauth.socialaccount.providers.github",
]

MIDDLEWARE = [
	"django.middleware.security.SecurityMiddleware",
	"django.contrib.sessions.middleware.SessionMiddleware",
	"corsheaders.middleware.CorsMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
	"prestige.middlewares.parsed_body.ParsedBodyMiddleware",
]

AUTH_USER_MODEL = "auth_api.User"

ROOT_URLCONF = "prestige.urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
				"django.template.context_processors.request",  # Added for django-allauth.
			],
		},
	},
]

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True

SOCIALACCOUNT_PROVIDERS = {
	"APP": {
		"client_id": os.environ.get("PRESTIGE_OAUTH_GITHUB_CLIENT_ID"),
		"secret": os.environ.get("PRESTIGE_OAUTH_GITHUB_CLIENT_SECRET"),
	} if "PRESTIGE_OAUTH_GITHUB_CLIENT_ID" in os.environ else {},
	"SCOPE": [
		"read:user",
		"user:email",
		"repo",
		"gist",
	],
}

WSGI_APPLICATION = "prestige.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DATABASES = {
	# This will parse the values of the PRESTIGE_DATABASE_URL environment variable into Django's DB config format.
	# For SQLite, set `PRESTIGE_DATABASE_URL=sqlite:///path/to/folder/db.sqlite3`
	"default": {
		"ENGINE": "django.db.backends.sqlite3",
		"NAME": ":memory:",
	} if UNIVERSE == "test" else dj_database_url.config(env="PRESTIGE_DATABASE_URL", conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
	},
	{
		"NAME": "prestige.password_validation.MaximumLengthValidator",
	},
]


# Logging
# https://docs.djangoproject.com/en/3.1/topics/logging/
LOGGING = {
	"version": 1,
	"disable_existing_loggers": False,
	"formatters": {
		"verbose": {
			"format": "{asctime} {levelname} {name} {message}",
			"style": "{",
			"datefmt": "%Y.%m.%d.%H.%M.%S.%j",
		},
	},
	"handlers": {
		"console": {
			"class": "logging.StreamHandler",
			"formatter": "verbose",
		},
		"mail_admins": {
			"level": "ERROR",
			"class": "django.utils.log.AdminEmailHandler",
		},
	},
	"loggers": {
		"django": {
			"handlers": ["console"],
			"level": "WARNING",
			"propagate": True,
		},
		"django.request": {
			"handlers": ["console", "mail_admins"],
			"level": "ERROR" if UNIVERSE == "test" else "DEBUG",
			"propagate": False,
		},
		"urllib3": {
			"handlers": ["console"],
			"level": "WARNING",
			"propagate": True,
		},
		"gunicorn.error": {
			"handlers": ["console"],
			"level": "INFO",
			"propagate": True,
		},
	},
	"root": {
		"handlers": ["console", "mail_admins"],
		"level": "ERROR" if UNIVERSE == "test" or not DEBUG else "DEBUG",
	},
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"


if UNIVERSE != "test":
	CORS_ALLOWED_ORIGINS = [s.strip() for s in os.getenv("PRESTIGE_CORS_ORIGINS", "").split(",") if not s.isspace()]
	CORS_ALLOW_CREDENTIALS = True


PROXY_DISALLOW_HOSTS = {
	s.strip()
	for s in os.getenv("PRESTIGE_PROXY_DISALLOW_HOSTS", "localhost, 127.0.0.1").split(",")
	if not s.isspace()
}
